# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./waifu_gallery.db:/app/waifu_gallery.db
      - ./sessions:/app/sessions
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    restart: unless-stopped
    depends_on:
      - scraper

  scraper:
    build: .
    command: python scraper.py
    volumes:
      - ./images:/app/images
      - ./waifu_gallery.db:/app/waifu_gallery.db
      - ./sessions:/app/sessions
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - TELEGRAM_CHANNEL=${TELEGRAM_CHANNEL}
      - SCRAPER_LIMIT=${SCRAPER_LIMIT:-100}
    restart: "no"  # Run once, don't restart
    profiles:
      - manual  # Only run when explicitly called

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped
    profiles:
      - production

